//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkflowAuthoring
{
    using System;
    using System.ComponentModel;
    using System.ComponentModel.Design;
    using System.Workflow.ComponentModel.Design;
    using System.Workflow.ComponentModel;
    using System.Workflow.ComponentModel.Serialization;
    using System.Workflow.ComponentModel.Compiler;
    using System.Drawing;
    using System.Collections;
    using System.Workflow.Activities;
    using System.Workflow.Runtime;
    
    
    public partial class CSVConnectorWorkflow : System.Workflow.Activities.SequentialWorkflowActivity
    {
        
        public static System.Workflow.ComponentModel.DependencyProperty ImportData_FormatFilePathProperty = DependencyProperty.Register("ImportData_FormatFilePath", typeof(System.String), typeof(WorkflowAuthoring.CSVConnectorWorkflow));
        
        public static System.Workflow.ComponentModel.DependencyProperty ImportData_DataFilePathProperty = DependencyProperty.Register("ImportData_DataFilePath", typeof(System.String), typeof(WorkflowAuthoring.CSVConnectorWorkflow));
        
        public string ImportData_FormatFilePath
        {
            get
            {
                return ((string)(base.GetValue(WorkflowAuthoring.CSVConnectorWorkflow.ImportData_FormatFilePathProperty)));
            }
            set
            {
                base.SetValue(WorkflowAuthoring.CSVConnectorWorkflow.ImportData_FormatFilePathProperty, value);
            }
        }
        
        public string ImportData_DataFilePath
        {
            get
            {
                return ((string)(base.GetValue(WorkflowAuthoring.CSVConnectorWorkflow.ImportData_DataFilePathProperty)));
            }
            set
            {
                base.SetValue(WorkflowAuthoring.CSVConnectorWorkflow.ImportData_DataFilePathProperty, value);
            }
        }
    }
}
